"""create initial schema

Revision ID: 4bd995617d1c
Revises:
Create Date: 2026-08-25 01:26:01.604532
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4bd995617d1c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player",
        sa.Column("external_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("team", sa.String(length=80), nullable=False),
        sa.Column(
            "role", sa.Enum("P", "D", "C", "A", name="role", native_enum=False), nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("external_id"),
    )
    op.create_table(
        "strategy",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "auction",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("initial_credits", sa.Integer(), nullable=False),
        sa.Column("goalkeeper_slots", sa.Integer(), nullable=False),
        sa.Column("defender_slots", sa.Integer(), nullable=False),
        sa.Column("midfielder_slots", sa.Integer(), nullable=False),
        sa.Column("forward_slots", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "live", "completed", name="auctionstatus", native_enum=False, length=10
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategy.uuid"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "tier",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("strategy_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role", sa.Enum("P", "D", "C", "A", name="role", native_enum=False), nullable=False
        ),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategy.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("strategy_id", "role", "name"),
        sa.UniqueConstraint("strategy_id", "role", "position"),
    )
    op.create_table(
        "participant",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("auction_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["auction_id"], ["auction.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("auction_id", "name"),
        sa.UniqueConstraint("auction_id", "position"),
    )
    op.create_table(
        "strategy_entry",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("strategy_id", sa.String(length=36), nullable=False),
        sa.Column("player_id", sa.String(length=32), nullable=False),
        sa.Column(
            "role", sa.Enum("P", "D", "C", "A", name="role", native_enum=False), nullable=False
        ),
        sa.Column("tier_id", sa.String(length=36), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.external_id"],
        ),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategy.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tier_id"], ["tier.uuid"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("strategy_id", "player_id"),
    )
    op.create_table(
        "purchase",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("auction_id", sa.String(length=36), nullable=False),
        sa.Column("player_id", sa.String(length=32), nullable=False),
        sa.Column("player_name", sa.String(length=120), nullable=False),
        sa.Column(
            "role", sa.Enum("P", "D", "C", "A", name="role", native_enum=False), nullable=False
        ),
        sa.Column("participant_id", sa.String(length=36), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.CheckConstraint("price >= 1"),
        sa.ForeignKeyConstraint(["auction_id"], ["auction.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participant.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.external_id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        "uq_active_purchase_player",
        "purchase",
        ["auction_id", "player_id"],
        unique=True,
        sqlite_where=sa.text("cancelled IS 0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_active_purchase_player", table_name="purchase", sqlite_where=sa.text("cancelled IS 0")
    )
    op.drop_table("purchase")
    op.drop_table("strategy_entry")
    op.drop_table("participant")
    op.drop_table("tier")
    op.drop_table("auction")
    op.drop_table("strategy")
    op.drop_table("player")
    # ### end Alembic commands ###
